### ISSUE TITLE
latin1 json response

### ISSUE THREAD

**Issue by spale75** [scurth/yoctopuce-munin#1]
I have a Yocto temperature sensor. Unfortunately VirtualHub seems to encode the JSON in latin1 which python fails to decode. As a workaround I have changed:

devicedata = json.loads(deviceresponse.read())
into
devicedata = json.loads(unicode(deviceresponse.read(),'latin-1'))

Now it works. I don't know if you want to fix this in the munin module or in VirtualHub (I think it would be better to send UTF8 anyway).

**Comment by scurth** [comment]
Thanks for this hint. I will look into this. Which OS and locales do you use?

Sascha

**Comment by spale75** [comment]
Hi Sascha,

I use Ubuntu server, UTF-8. But I just got a response from Yoctopuce guys, you can safely change your code to decode the JSON as iso-8859-1, they told me the encoding was a choice. So it is not unset or some default, they choose it and do not plan to change it. They will, however, fix the HTTP header a send a proper content-type encoding ;)

**Comment by scurth** [comment]
Change implemented.
